/* ============================================================
   CUSTOMER DETAIL REPORT — 36-MONTH MONTHLY / QUARTERLY / YEARLY
   Generated for report date: 2026-03-04
   ─────────────────────────────────────────────────────────────
   Monthly:   April 2023 → March 2026  (36 months, M01 = most recent)
   Quarterly: Q2 2023    → Q1 2026     (12 quarters)
   Yearly:    Full Year 2023 → Full Year 2026 (YTD)

   Outside Sales Rep: CMSLMN from CUSTMAST
   DB: DB2/AS400, schema GSFL2K
   ============================================================ */

WITH
EMAILS AS (
    SELECT
        X.CCNXACCT       AS ACCT,
        MIN(C.CNCE_MAIL) AS EMAIL
    FROM GSFL2K.CONTXREF X
    JOIN GSFL2K.CONTCONT C
        ON C.CNCCONTID = X.CCNXCONTID
    GROUP BY X.CCNXACCT
),

AGG AS (
    SELECT
        TRIM(H.SHCUST) AS CUSTOMER_NUMBER,

        /* ══════════════════════════════════════════════════════
           MONTHLY SALES  (most recent → oldest)
           ══════════════════════════════════════════════════════ */
        SUM(CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MARCH_2026,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 2 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FEBRUARY_2026,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 1 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JANUARY_2026,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_DECEMBER_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=11 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_NOVEMBER_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=10 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_OCTOBER_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_SEPTEMBER_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 8 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_AUGUST_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 7 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JULY_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JUNE_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 5 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MAY_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 4 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_APRIL_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MARCH_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 2 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FEBRUARY_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 1 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JANUARY_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_DECEMBER_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=11 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_NOVEMBER_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=10 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_OCTOBER_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_SEPTEMBER_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 8 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_AUGUST_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 7 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JULY_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JUNE_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 5 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MAY_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 4 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_APRIL_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MARCH_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 2 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FEBRUARY_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 1 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JANUARY_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_DECEMBER_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=11 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_NOVEMBER_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=10 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_OCTOBER_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_SEPTEMBER_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 8 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_AUGUST_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 7 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JULY_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_JUNE_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 5 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_MAY_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 4 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_APRIL_2023,

        /* ══════════════════════════════════════════════════════
           QUARTERLY SALES  (most recent → oldest)
           ══════════════════════════════════════════════════════ */
        SUM(CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q1_2026,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q4_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q3_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q2_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q1_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q4_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q3_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q2_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q1_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q4_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q3_2023,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_Q2_2023,

        /* ══════════════════════════════════════════════════════
           YEARLY SALES
           ══════════════════════════════════════════════════════ */
        SUM(CASE WHEN YEAR(H.SHIDAT)=2026 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FULL_YEAR_2026,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2025 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FULL_YEAR_2025,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2024 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FULL_YEAR_2024,
        SUM(CASE WHEN YEAR(H.SHIDAT)=2023 THEN COALESCE(L.SLENET,0) ELSE 0 END) AS SALES_FULL_YEAR_2023,

        /* ══════════════════════════════════════════════════════
           MONTHLY ORDERS  (distinct invoice key per month)
           ══════════════════════════════════════════════════════ */
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MARCH_2026,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 2 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FEBRUARY_2026,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT)= 1 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JANUARY_2026,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_DECEMBER_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=11 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_NOVEMBER_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)=10 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_OCTOBER_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_SEPTEMBER_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 8 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_AUGUST_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 7 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JULY_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JUNE_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 5 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MAY_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 4 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_APRIL_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MARCH_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 2 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FEBRUARY_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT)= 1 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JANUARY_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_DECEMBER_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=11 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_NOVEMBER_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)=10 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_OCTOBER_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_SEPTEMBER_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 8 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_AUGUST_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 7 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JULY_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JUNE_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 5 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MAY_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 4 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_APRIL_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MARCH_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 2 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FEBRUARY_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT)= 1 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JANUARY_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_DECEMBER_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=11 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_NOVEMBER_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)=10 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_OCTOBER_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_SEPTEMBER_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 8 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_AUGUST_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 7 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JULY_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_JUNE_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 5 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_MAY_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT)= 4 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_APRIL_2023,

        /* ══════════════════════════════════════════════════════
           QUARTERLY ORDERS
           ══════════════════════════════════════════════════════ */
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2026 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q1_2026,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q4_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q3_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q2_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q1_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q4_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q3_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q2_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 AND MONTH(H.SHIDAT) BETWEEN  1 AND  3 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q1_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN 10 AND 12 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q4_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN  7 AND  9 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q3_2023,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 AND MONTH(H.SHIDAT) BETWEEN  4 AND  6 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_Q2_2023,

        /* ══════════════════════════════════════════════════════
           YEARLY ORDERS
           ══════════════════════════════════════════════════════ */
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2026 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FULL_YEAR_2026,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2025 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FULL_YEAR_2025,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2024 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FULL_YEAR_2024,
        COUNT(DISTINCT CASE WHEN YEAR(H.SHIDAT)=2023 THEN RTRIM(CHAR(H.SHCO))||'|'||RTRIM(CHAR(H.SHLOC))||'|'||RTRIM(CHAR(H.SHINV#)) END) AS ORDERS_FULL_YEAR_2023

    FROM GSFL2K.SHHEAD H
    JOIN GSFL2K.SHLINE L
        ON  L.SLCO   = H.SHCO
        AND L.SLLOC  = H.SHLOC
        AND L.SLINV# = H.SHINV#
        AND L.SLORD# = H.SHORD#
    WHERE YEAR(H.SHIDAT) >= 2023
    GROUP BY TRIM(H.SHCUST)
)

SELECT
    /* ── Customer Identity ── */
    TRIM(C.CMCUST) AS CUSTOMER_NUMBER,
    TRIM(C.CMNAME) AS CUSTOMER_NAME,
    TRIM(C.CMADR1) AS ADDRESS_LINE_1,
    TRIM(C.CMADR2) AS ADDRESS_LINE_2,
    TRIM(C.CMADR3) AS ADDRESS_LINE_3,
    TRIM(C.CMZIP)  AS ZIP_CODE,
    TRIM(C.CMATTN) AS CONTACT_NAME,
    TRIM(C.CMPHON) AS PHONE_NUMBER,
    TRIM(COALESCE(E.EMAIL, '')) AS EMAIL,
    TRIM(C.CMCLAS) AS CUSTOMER_CLASS,
    TRIM(C.CMSLMN) AS OUTSIDE_SALES_REP,

    /* ── Monthly Sales ── */
    COALESCE(A.SALES_MARCH_2026,     0) AS SALES_MARCH_2026,
    COALESCE(A.SALES_FEBRUARY_2026,  0) AS SALES_FEBRUARY_2026,
    COALESCE(A.SALES_JANUARY_2026,   0) AS SALES_JANUARY_2026,
    COALESCE(A.SALES_DECEMBER_2025,  0) AS SALES_DECEMBER_2025,
    COALESCE(A.SALES_NOVEMBER_2025,  0) AS SALES_NOVEMBER_2025,
    COALESCE(A.SALES_OCTOBER_2025,   0) AS SALES_OCTOBER_2025,
    COALESCE(A.SALES_SEPTEMBER_2025, 0) AS SALES_SEPTEMBER_2025,
    COALESCE(A.SALES_AUGUST_2025,    0) AS SALES_AUGUST_2025,
    COALESCE(A.SALES_JULY_2025,      0) AS SALES_JULY_2025,
    COALESCE(A.SALES_JUNE_2025,      0) AS SALES_JUNE_2025,
    COALESCE(A.SALES_MAY_2025,       0) AS SALES_MAY_2025,
    COALESCE(A.SALES_APRIL_2025,     0) AS SALES_APRIL_2025,
    COALESCE(A.SALES_MARCH_2025,     0) AS SALES_MARCH_2025,
    COALESCE(A.SALES_FEBRUARY_2025,  0) AS SALES_FEBRUARY_2025,
    COALESCE(A.SALES_JANUARY_2025,   0) AS SALES_JANUARY_2025,
    COALESCE(A.SALES_DECEMBER_2024,  0) AS SALES_DECEMBER_2024,
    COALESCE(A.SALES_NOVEMBER_2024,  0) AS SALES_NOVEMBER_2024,
    COALESCE(A.SALES_OCTOBER_2024,   0) AS SALES_OCTOBER_2024,
    COALESCE(A.SALES_SEPTEMBER_2024, 0) AS SALES_SEPTEMBER_2024,
    COALESCE(A.SALES_AUGUST_2024,    0) AS SALES_AUGUST_2024,
    COALESCE(A.SALES_JULY_2024,      0) AS SALES_JULY_2024,
    COALESCE(A.SALES_JUNE_2024,      0) AS SALES_JUNE_2024,
    COALESCE(A.SALES_MAY_2024,       0) AS SALES_MAY_2024,
    COALESCE(A.SALES_APRIL_2024,     0) AS SALES_APRIL_2024,
    COALESCE(A.SALES_MARCH_2024,     0) AS SALES_MARCH_2024,
    COALESCE(A.SALES_FEBRUARY_2024,  0) AS SALES_FEBRUARY_2024,
    COALESCE(A.SALES_JANUARY_2024,   0) AS SALES_JANUARY_2024,
    COALESCE(A.SALES_DECEMBER_2023,  0) AS SALES_DECEMBER_2023,
    COALESCE(A.SALES_NOVEMBER_2023,  0) AS SALES_NOVEMBER_2023,
    COALESCE(A.SALES_OCTOBER_2023,   0) AS SALES_OCTOBER_2023,
    COALESCE(A.SALES_SEPTEMBER_2023, 0) AS SALES_SEPTEMBER_2023,
    COALESCE(A.SALES_AUGUST_2023,    0) AS SALES_AUGUST_2023,
    COALESCE(A.SALES_JULY_2023,      0) AS SALES_JULY_2023,
    COALESCE(A.SALES_JUNE_2023,      0) AS SALES_JUNE_2023,
    COALESCE(A.SALES_MAY_2023,       0) AS SALES_MAY_2023,
    COALESCE(A.SALES_APRIL_2023,     0) AS SALES_APRIL_2023,

    /* ── Quarterly Sales ── */
    COALESCE(A.SALES_Q1_2026, 0) AS SALES_Q1_2026,
    COALESCE(A.SALES_Q4_2025, 0) AS SALES_Q4_2025,
    COALESCE(A.SALES_Q3_2025, 0) AS SALES_Q3_2025,
    COALESCE(A.SALES_Q2_2025, 0) AS SALES_Q2_2025,
    COALESCE(A.SALES_Q1_2025, 0) AS SALES_Q1_2025,
    COALESCE(A.SALES_Q4_2024, 0) AS SALES_Q4_2024,
    COALESCE(A.SALES_Q3_2024, 0) AS SALES_Q3_2024,
    COALESCE(A.SALES_Q2_2024, 0) AS SALES_Q2_2024,
    COALESCE(A.SALES_Q1_2024, 0) AS SALES_Q1_2024,
    COALESCE(A.SALES_Q4_2023, 0) AS SALES_Q4_2023,
    COALESCE(A.SALES_Q3_2023, 0) AS SALES_Q3_2023,
    COALESCE(A.SALES_Q2_2023, 0) AS SALES_Q2_2023,

    /* ── Yearly Sales ── */
    COALESCE(A.SALES_FULL_YEAR_2026, 0) AS SALES_FULL_YEAR_2026,
    COALESCE(A.SALES_FULL_YEAR_2025, 0) AS SALES_FULL_YEAR_2025,
    COALESCE(A.SALES_FULL_YEAR_2024, 0) AS SALES_FULL_YEAR_2024,
    COALESCE(A.SALES_FULL_YEAR_2023, 0) AS SALES_FULL_YEAR_2023,

    /* ── Monthly Orders ── */
    COALESCE(A.ORDERS_MARCH_2026,     0) AS ORDERS_MARCH_2026,
    COALESCE(A.ORDERS_FEBRUARY_2026,  0) AS ORDERS_FEBRUARY_2026,
    COALESCE(A.ORDERS_JANUARY_2026,   0) AS ORDERS_JANUARY_2026,
    COALESCE(A.ORDERS_DECEMBER_2025,  0) AS ORDERS_DECEMBER_2025,
    COALESCE(A.ORDERS_NOVEMBER_2025,  0) AS ORDERS_NOVEMBER_2025,
    COALESCE(A.ORDERS_OCTOBER_2025,   0) AS ORDERS_OCTOBER_2025,
    COALESCE(A.ORDERS_SEPTEMBER_2025, 0) AS ORDERS_SEPTEMBER_2025,
    COALESCE(A.ORDERS_AUGUST_2025,    0) AS ORDERS_AUGUST_2025,
    COALESCE(A.ORDERS_JULY_2025,      0) AS ORDERS_JULY_2025,
    COALESCE(A.ORDERS_JUNE_2025,      0) AS ORDERS_JUNE_2025,
    COALESCE(A.ORDERS_MAY_2025,       0) AS ORDERS_MAY_2025,
    COALESCE(A.ORDERS_APRIL_2025,     0) AS ORDERS_APRIL_2025,
    COALESCE(A.ORDERS_MARCH_2025,     0) AS ORDERS_MARCH_2025,
    COALESCE(A.ORDERS_FEBRUARY_2025,  0) AS ORDERS_FEBRUARY_2025,
    COALESCE(A.ORDERS_JANUARY_2025,   0) AS ORDERS_JANUARY_2025,
    COALESCE(A.ORDERS_DECEMBER_2024,  0) AS ORDERS_DECEMBER_2024,
    COALESCE(A.ORDERS_NOVEMBER_2024,  0) AS ORDERS_NOVEMBER_2024,
    COALESCE(A.ORDERS_OCTOBER_2024,   0) AS ORDERS_OCTOBER_2024,
    COALESCE(A.ORDERS_SEPTEMBER_2024, 0) AS ORDERS_SEPTEMBER_2024,
    COALESCE(A.ORDERS_AUGUST_2024,    0) AS ORDERS_AUGUST_2024,
    COALESCE(A.ORDERS_JULY_2024,      0) AS ORDERS_JULY_2024,
    COALESCE(A.ORDERS_JUNE_2024,      0) AS ORDERS_JUNE_2024,
    COALESCE(A.ORDERS_MAY_2024,       0) AS ORDERS_MAY_2024,
    COALESCE(A.ORDERS_APRIL_2024,     0) AS ORDERS_APRIL_2024,
    COALESCE(A.ORDERS_MARCH_2024,     0) AS ORDERS_MARCH_2024,
    COALESCE(A.ORDERS_FEBRUARY_2024,  0) AS ORDERS_FEBRUARY_2024,
    COALESCE(A.ORDERS_JANUARY_2024,   0) AS ORDERS_JANUARY_2024,
    COALESCE(A.ORDERS_DECEMBER_2023,  0) AS ORDERS_DECEMBER_2023,
    COALESCE(A.ORDERS_NOVEMBER_2023,  0) AS ORDERS_NOVEMBER_2023,
    COALESCE(A.ORDERS_OCTOBER_2023,   0) AS ORDERS_OCTOBER_2023,
    COALESCE(A.ORDERS_SEPTEMBER_2023, 0) AS ORDERS_SEPTEMBER_2023,
    COALESCE(A.ORDERS_AUGUST_2023,    0) AS ORDERS_AUGUST_2023,
    COALESCE(A.ORDERS_JULY_2023,      0) AS ORDERS_JULY_2023,
    COALESCE(A.ORDERS_JUNE_2023,      0) AS ORDERS_JUNE_2023,
    COALESCE(A.ORDERS_MAY_2023,       0) AS ORDERS_MAY_2023,
    COALESCE(A.ORDERS_APRIL_2023,     0) AS ORDERS_APRIL_2023,

    /* ── Quarterly Orders ── */
    COALESCE(A.ORDERS_Q1_2026, 0) AS ORDERS_Q1_2026,
    COALESCE(A.ORDERS_Q4_2025, 0) AS ORDERS_Q4_2025,
    COALESCE(A.ORDERS_Q3_2025, 0) AS ORDERS_Q3_2025,
    COALESCE(A.ORDERS_Q2_2025, 0) AS ORDERS_Q2_2025,
    COALESCE(A.ORDERS_Q1_2025, 0) AS ORDERS_Q1_2025,
    COALESCE(A.ORDERS_Q4_2024, 0) AS ORDERS_Q4_2024,
    COALESCE(A.ORDERS_Q3_2024, 0) AS ORDERS_Q3_2024,
    COALESCE(A.ORDERS_Q2_2024, 0) AS ORDERS_Q2_2024,
    COALESCE(A.ORDERS_Q1_2024, 0) AS ORDERS_Q1_2024,
    COALESCE(A.ORDERS_Q4_2023, 0) AS ORDERS_Q4_2023,
    COALESCE(A.ORDERS_Q3_2023, 0) AS ORDERS_Q3_2023,
    COALESCE(A.ORDERS_Q2_2023, 0) AS ORDERS_Q2_2023,

    /* ── Yearly Orders ── */
    COALESCE(A.ORDERS_FULL_YEAR_2026, 0) AS ORDERS_FULL_YEAR_2026,
    COALESCE(A.ORDERS_FULL_YEAR_2025, 0) AS ORDERS_FULL_YEAR_2025,
    COALESCE(A.ORDERS_FULL_YEAR_2024, 0) AS ORDERS_FULL_YEAR_2024,
    COALESCE(A.ORDERS_FULL_YEAR_2023, 0) AS ORDERS_FULL_YEAR_2023

FROM GSFL2K.CUSTMAST C
LEFT JOIN EMAILS E
    ON E.ACCT = C.CMCUST
LEFT JOIN AGG A
    ON A.CUSTOMER_NUMBER = TRIM(C.CMCUST)
ORDER BY TRIM(C.CMCUST)
