/* ============================================================
   CUSTOMER DASHBOARD QUERY + CUSTOMER_BUCKETS (Power Query safe)
   Changes requested:
   - High Value: Top 250 customers by trailing-365 sales (not top X share)
   - Growing: Any customer with SALES_YTD >= 1.20 * SALES_PRIOR_YTD
   - Pricing flag columns (Yes/No) derived from PRICEXCP PEDESC values:
       DISPLAYING_DEALER, DESIGNER_GC, OUT_OF_STATE, UPCHARGE,
       SUNDRIES_MOULDINGS, PROSOURCE, VIP
   ============================================================ */

WITH
PARAMS AS (
    SELECT
        ADD_MONTHS(CURRENT_DATE, -6)  AS SIX_MONTHS_AGO,
        DATE(VARCHAR_FORMAT(CURRENT_DATE, 'YYYY') || '-01-01') AS YEAR_START,
        DATE(VARCHAR_FORMAT(ADD_MONTHS(CURRENT_DATE, -12), 'YYYY') || '-01-01') AS PRIOR_YEAR_START,
        ADD_MONTHS(CURRENT_DATE, -12) AS SAME_DAY_LAST_YEAR
    FROM SYSIBM.SYSDUMMY1
),

EMAILS AS (
    SELECT
        X.CCNXACCT AS ACCT,
        MIN(C.CNCE_MAIL) AS EMAIL
    FROM GSFL2K.CONTXREF X
    JOIN GSFL2K.CONTCONT C
        ON C.CNCCONTID = X.CCNXCONTID
    GROUP BY X.CCNXACCT
),

PRICING_FLAGS AS (
    -- One row per customer. Each flag is Yes if ANY active pricing record
    -- matches the listed tier names, No otherwise.
    SELECT
        TRIM(PECUST) AS CUSTOMER_NUMBER,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'ALLORA DISPLAYING DEALER',
            'AQUABLUE DISPLAYING DEALER',
            'BELLAGIO',
            'BELLISIMO',
            'BEVERLY HILLS DISP. DEALER',
            'BIG SKY',
            'CANTINA',
            'CANYON CREST',
            'CLIFFSIDE B.BLONDE/COOL MIST',
            'CLIFFSIDE STILLWATER',
            'COMPETITON BUSTER',
            'CONT.CHOICE R/O 2-1/4"',
            'CONT.CHOICE W/O 2-1/4"',
            'CONT.CHOICE W/O 5"',
            'CONT.CHOICE W/O 7"',
            'CONT.CHOICE WALNUT 5"',
            'CONT.CHOICE WALNUT 7"',
            'CONTRACTORS CHOICE',
            'CRYSTAL VALLEY',
            'GOLD LABEL DISPLAYING DEALER',
            'GVWPC',
            'ILLUMIN8 DIS.DEALER & SPIFF',
            'ILLUMIN8 DISPLAYING DEALER',
            'ILLUMIN8 DISPLAYING DELAER',
            'LEGENDS DISPLAYING DEALER',
            'PRIVATE DIS.DEALER',
            'PRIVATE SELECTION DISP. DEALER',
            'VINYLNOVA DISPLAYING DEALER',
            'VINYLNOVA HB + $0.30 SPIFF',
            'VINYLNOVA PLANK + $0.30 SPIFF'
        ) THEN 'Yes' ELSE 'No' END) AS DISPLAYING_DEALER,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'DESIGNER PRICING',
            'GENERAL CONTRACTOR PRICING'
        ) THEN 'Yes' ELSE 'No' END) AS DESIGNER_GC,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'FLORIDA PRICING',
            'FLORIDA PRICING <250 SQFT',
            'FLORIDA PRICING >=1000 SQFT',
            'FLORIDA PRICING 250-999 SQFT',
            'LAS VEGAS PRICING',
            'LAS VEGAS VIP PRICING',
            'TEXAS CUSTOMER',
            'TEXAS PRICING'
        ) THEN 'Yes' ELSE 'No' END) AS OUT_OF_STATE,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            '$0.20 FREIGHT UPCHARGE',
            'PREFERRED + $0.20',
            'PREFERRED + $1.00',
            'PREFERRED + $1.00 PER JIM/YONI',
            'PREFERRED + $2.00',
            'PREFERRED + $2.00/DESIGNER $$$',
            'PREFERRED + $2.50',
            'PREFERRED + 20¢',
            'PREFERRED + 25% PER YONI/BRAD',
            'PREFERRED + 50¢',
            'UPCHARGE + 10%'
        ) THEN 'Yes' ELSE 'No' END) AS UPCHARGE,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'BOSTIK FILE BACK GREENFORCE',
            'BOSTIK FILE BACK SL-GYP',
            'BOSTIK FLIE BACK SL-GYP',
            'BOSTIK VAPOR LOCK',
            'BOSTIL FILE BACK SL-GYP',
            'DRITAC SUREBOND 7300',
            'OMP 9000',
            'OMP 9000 HYBRID URETHANE ADH',
            'PRIME BASE SHOE',
            'RAGS DISCOUNT -10% RAFL10',
            'RAGS DISCOUNT -10% RAFL5',
            'RAGS DISCOUNT -10% RAFL50',
            'RAGS DISCOUNT -10% RATO10',
            'RAGS DISCOUNT -10% RATO5',
            'SL DISCOUNT -10% UNBO602411',
            'SL DISCOUNT -10% UNBO602428'
        ) THEN 'Yes' ELSE 'No' END) AS SUNDRIES_MOULDINGS,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'PROSOURCE CA GROUP',
            'PROSOURCE CALIFORNIA GROUP',
            'PROSOURCE CALIFRONIA GROUP',
            'PROSOURCE TEXAS GROUP',
            'PROSOURCE TX GROUP'
        ) THEN 'Yes' ELSE 'No' END) AS PROSOURCE,

        MAX(CASE WHEN TRIM(PEDESC) IN (
            'VIP CUSTOMER',
            'VIP PRICING',
            'VIP PRICING + 20¢',
            'VIP PRICING LABEL'
        ) THEN 'Yes' ELSE 'No' END) AS VIP,

        MIN(CASE WHEN TRIM(PEDESC) IN (
            'VIP CUSTOMER',
            'VIP PRICING',
            'VIP PRICING + 20¢',
            'VIP PRICING LABEL'
        ) THEN PESDAT END) AS VIP_START_DATE

    FROM GSFL2K.PRICEXCP
    WHERE PESDAT <= CURRENT_DATE
      AND PEEDAT  >= CURRENT_DATE
    GROUP BY TRIM(PECUST)
),

AGG AS (
    SELECT
        TRIM(H.SHCUST) AS CUSTOMER_NUMBER,

        MIN(H.SHIDAT) AS FIRST_ORDER_DATE,
        MAX(H.SHIDAT) AS LAST_ORDER_DATE,

        /* Sales */
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 30 DAYS)  THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_30D,
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 90 DAYS)  THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_90D,
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 180 DAYS) THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_180D,
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 365 DAYS) THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_365D,
        SUM(CASE WHEN H.SHIDAT >= DATE('2020-01-01') AND H.SHIDAT <= DATE('2020-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2020,
        SUM(CASE WHEN H.SHIDAT >= DATE('2021-01-01') AND H.SHIDAT <= DATE('2021-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2021,
        SUM(CASE WHEN H.SHIDAT >= DATE('2022-01-01') AND H.SHIDAT <= DATE('2022-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2022,
        SUM(CASE WHEN H.SHIDAT >= DATE('2023-01-01') AND H.SHIDAT <= DATE('2023-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2023,
        SUM(CASE WHEN H.SHIDAT >= DATE('2024-01-01') AND H.SHIDAT <= DATE('2024-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2024,
        SUM(CASE WHEN H.SHIDAT >= DATE('2025-01-01') AND H.SHIDAT <= DATE('2025-12-31') THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_2025,
        SUM(COALESCE(L.SLENET, 0)) AS SALES_LIFETIME,

        /* Prior window for At Risk comparisons */
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 360 DAYS)
                  AND H.SHIDAT <  (CURRENT_DATE - 180 DAYS)
                 THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_PREV_180D,

        /* YTD and prior YTD (same day last year) */
        SUM(CASE WHEN H.SHIDAT >= P.YEAR_START
                  AND H.SHIDAT <= CURRENT_DATE
                 THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_YTD,

        SUM(CASE WHEN H.SHIDAT >= P.PRIOR_YEAR_START
                  AND H.SHIDAT <= P.SAME_DAY_LAST_YEAR
                 THEN COALESCE(L.SLENET, 0) ELSE 0 END) AS SALES_PRIOR_YTD,

        /* SF */
        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 30 DAYS)
                  AND TRIM(L.SLUM2) = 'SF'
                 THEN COALESCE(L.SLBLUO, 0) ELSE 0 END) AS SF_30D,

        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 90 DAYS)
                  AND TRIM(L.SLUM2) = 'SF'
                 THEN COALESCE(L.SLBLUO, 0) ELSE 0 END) AS SF_90D,

        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 180 DAYS)
                  AND TRIM(L.SLUM2) = 'SF'
                 THEN COALESCE(L.SLBLUO, 0) ELSE 0 END) AS SF_180D,

        SUM(CASE WHEN H.SHIDAT >= (CURRENT_DATE - 365 DAYS)
                  AND TRIM(L.SLUM2) = 'SF'
                 THEN COALESCE(L.SLBLUO, 0) ELSE 0 END) AS SF_365D,

        SUM(CASE WHEN TRIM(L.SLUM2) = 'SF'
                 THEN COALESCE(L.SLBLUO, 0) ELSE 0 END) AS SF_LIFETIME,

        /* Orders (distinct invoice key) */
        COUNT(DISTINCT CASE WHEN H.SHIDAT >= (CURRENT_DATE - 30 DAYS)
            THEN (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#))) END) AS ORDERS_30D,

        COUNT(DISTINCT CASE WHEN H.SHIDAT >= (CURRENT_DATE - 90 DAYS)
            THEN (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#))) END) AS ORDERS_90D,

        COUNT(DISTINCT CASE WHEN H.SHIDAT >= (CURRENT_DATE - 180 DAYS)
            THEN (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#))) END) AS ORDERS_180D,

        COUNT(DISTINCT CASE WHEN H.SHIDAT >= (CURRENT_DATE - 365 DAYS)
            THEN (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#))) END) AS ORDERS_365D,

        COUNT(DISTINCT (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#)))) AS ORDERS_LIFETIME,

        COUNT(DISTINCT CASE WHEN H.SHIDAT >= (CURRENT_DATE - 360 DAYS)
                             AND H.SHIDAT <  (CURRENT_DATE - 180 DAYS)
            THEN (RTRIM(CHAR(H.SHCO)) || '|' || RTRIM(CHAR(H.SHLOC)) || '|' || RTRIM(CHAR(H.SHINV#))) END) AS ORDERS_PREV_180D

    FROM GSFL2K.SHHEAD H
    JOIN GSFL2K.SHLINE L
      ON L.SLCO   = H.SHCO
     AND L.SLLOC  = H.SHLOC
     AND L.SLINV# = H.SHINV#
     AND L.SLORD# = H.SHORD#
    JOIN PARAMS P
      ON 1 = 1
    GROUP BY TRIM(H.SHCUST)
),

HV AS (
    SELECT
        A.*,
        ROW_NUMBER() OVER (
            ORDER BY COALESCE(A.SALES_365D, 0) DESC, A.CUSTOMER_NUMBER
        ) AS HV_RANK
    FROM AGG A
)

SELECT
    TRIM(C.CMCUST) AS CUSTOMER_NUMBER,
    TRIM(C.CMNAME) AS CUSTOMER_NAME,
    TRIM(C.CMADR1) AS ADDRESS_LINE_1,
    TRIM(C.CMADR2) AS ADDRESS_LINE_2,
    TRIM(C.CMADR3) AS ADDRESS_LINE_3,
    TRIM(C.CMZIP)  AS ZIPCODE,
    TRIM(C.CMATTN) AS CONTACT_NAME,
    TRIM(C.CMPHON) AS PHONE_NUMBER,
    TRIM(COALESCE(E.EMAIL, '')) AS EMAIL,
    TRIM(C.CMCLAS) AS CUSTOMER_CLASS,
    TRIM(C.CMSLMN) AS SALES_REP_NUMBER,
    TRIM(COALESCE(SM.SMNAME, '')) AS SALES_REP_NAME,

    COALESCE(PF.DISPLAYING_DEALER,  'No') AS DISPLAYING_DEALER,
    COALESCE(PF.DESIGNER_GC,        'No') AS DESIGNER_GC,
    COALESCE(PF.OUT_OF_STATE,       'No') AS OUT_OF_STATE,
    COALESCE(PF.UPCHARGE,           'No') AS UPCHARGE,
    COALESCE(PF.SUNDRIES_MOULDINGS, 'No') AS SUNDRIES_MOULDINGS,
    COALESCE(PF.PROSOURCE,          'No') AS PROSOURCE,
    COALESCE(PF.VIP,                'No') AS VIP,
    PF.VIP_START_DATE                     AS VIP_START_DATE,

    COALESCE(H.SALES_30D, 0)      AS SALES_30D,
    COALESCE(H.SALES_90D, 0)      AS SALES_90D,
    COALESCE(H.SALES_180D, 0)     AS SALES_180D,
    COALESCE(H.SALES_365D, 0)     AS SALES_365D,
    COALESCE(H.SALES_2020, 0)     AS SALES_2020,
    COALESCE(H.SALES_2021, 0)     AS SALES_2021,
    COALESCE(H.SALES_2022, 0)     AS SALES_2022,
    COALESCE(H.SALES_2023, 0)     AS SALES_2023,
    COALESCE(H.SALES_2024, 0)     AS SALES_2024,
    COALESCE(H.SALES_2025, 0)     AS SALES_2025,
    COALESCE(H.SALES_LIFETIME, 0) AS SALES_LIFETIME,

    COALESCE(H.ORDERS_30D, 0)      AS ORDERS_30D,
    COALESCE(H.ORDERS_90D, 0)      AS ORDERS_90D,
    COALESCE(H.ORDERS_180D, 0)     AS ORDERS_180D,
    COALESCE(H.ORDERS_365D, 0)     AS ORDERS_365D,
    COALESCE(H.ORDERS_LIFETIME, 0) AS ORDERS_LIFETIME,

    COALESCE(H.SF_30D, 0)      AS SF_30D,
    COALESCE(H.SF_90D, 0)      AS SF_90D,
    COALESCE(H.SF_180D, 0)     AS SF_180D,
    COALESCE(H.SF_365D, 0)     AS SF_365D,
    COALESCE(H.SF_LIFETIME, 0) AS SF_LIFETIME,

    DECIMAL(COALESCE(H.SALES_30D, 0)      / NULLIF(H.ORDERS_30D, 0), 18, 2) AS AVG_DOLLARS_PER_ORDER_30D,
    DECIMAL(COALESCE(H.SALES_90D, 0)      / NULLIF(H.ORDERS_90D, 0), 18, 2) AS AVG_DOLLARS_PER_ORDER_90D,
    DECIMAL(COALESCE(H.SALES_365D, 0)     / NULLIF(H.ORDERS_365D, 0), 18, 2) AS AVG_DOLLARS_PER_ORDER_365D,
    DECIMAL(COALESCE(H.SALES_LIFETIME, 0) / NULLIF(H.ORDERS_LIFETIME, 0), 18, 2) AS AVG_DOLLARS_PER_ORDER_LIFETIME,

    DECIMAL(COALESCE(H.SF_30D, 0)      / NULLIF(H.ORDERS_30D, 0), 18, 2) AS AVG_SF_PER_ORDER_30D,
    DECIMAL(COALESCE(H.SF_90D, 0)      / NULLIF(H.ORDERS_90D, 0), 18, 2) AS AVG_SF_PER_ORDER_90D,
    DECIMAL(COALESCE(H.SF_365D, 0)     / NULLIF(H.ORDERS_365D, 0), 18, 2) AS AVG_SF_PER_ORDER_365D,
    DECIMAL(COALESCE(H.SF_LIFETIME, 0) / NULLIF(H.ORDERS_LIFETIME, 0), 18, 2) AS AVG_SF_PER_ORDER_LIFETIME,

    CASE
        WHEN H.LAST_ORDER_DATE IS NULL THEN NULL
        ELSE (DAYS(CURRENT_DATE) - DAYS(H.LAST_ORDER_DATE))
    END AS DAYS_SINCE_LAST_ORDER,

    CASE
        WHEN H.FIRST_ORDER_DATE IS NULL OR H.LAST_ORDER_DATE IS NULL THEN NULL
        WHEN H.ORDERS_LIFETIME <= 1 THEN NULL
        ELSE DECIMAL(
            (DAYS(H.LAST_ORDER_DATE) - DAYS(H.FIRST_ORDER_DATE)) / NULLIF((H.ORDERS_LIFETIME - 1), 0),
            18, 2
        )
    END AS AVG_DAYS_PER_ORDER,

    CASE
        WHEN COALESCE(H.SALES_365D, 0) > 0
             AND H.HV_RANK <= 250
        THEN 'High Value'

        WHEN C.CMSDAT IS NOT NULL
             AND C.CMSDAT >= (SELECT SIX_MONTHS_AGO FROM PARAMS)
        THEN 'New'

        WHEN COALESCE(H.SALES_PRIOR_YTD, 0) > 0
             AND (COALESCE(H.SALES_YTD, 0) / NULLIF(H.SALES_PRIOR_YTD, 0)) >= 1.20
        THEN 'Growing'

        WHEN (
              COALESCE(H.SALES_PREV_180D, 0) >= 1000
              AND COALESCE(H.SALES_180D, 0) < 0.75 * COALESCE(H.SALES_PREV_180D, 0)
             )
          OR (
              COALESCE(H.ORDERS_PREV_180D, 0) >= 3
              AND COALESCE(H.ORDERS_180D, 0) < 0.75 * COALESCE(H.ORDERS_PREV_180D, 0)
             )
          OR (
              COALESCE(H.SALES_180D, 0) < 500
              AND COALESCE(H.ORDERS_180D, 0) < 2
              AND COALESCE(H.SALES_365D, 0) > 0
             )
        THEN 'At Risk'

        WHEN COALESCE(H.SALES_180D, 0) = 0
             AND COALESCE(H.ORDERS_180D, 0) = 0
        THEN 'Lost'

        WHEN COALESCE(H.SALES_90D, 0) > 0
             AND COALESCE(H.ORDERS_90D, 0) > 0
             AND COALESCE(H.SALES_30D, 0) BETWEEN 0.70 * (COALESCE(H.SALES_90D, 0) / 3) AND 1.30 * (COALESCE(H.SALES_90D, 0) / 3)
             AND COALESCE(H.ORDERS_30D, 0) BETWEEN 0.70 * (DECIMAL(COALESCE(H.ORDERS_90D, 0), 18, 2) / 3) AND 1.30 * (DECIMAL(COALESCE(H.ORDERS_90D, 0), 18, 2) / 3)
        THEN 'Regular'

        ELSE 'Regular'
    END AS CUSTOMER_BUCKETS

FROM GSFL2K.CUSTMAST C
LEFT JOIN EMAILS E
  ON E.ACCT = C.CMCUST
LEFT JOIN HV H
  ON H.CUSTOMER_NUMBER = TRIM(C.CMCUST)
LEFT JOIN PRICING_FLAGS PF
  ON PF.CUSTOMER_NUMBER = TRIM(C.CMCUST)
LEFT JOIN GSFL2K.SALESMAN SM
  ON TRIM(CHAR(SM.SMNO)) = TRIM(C.CMSLMN)
ORDER BY TRIM(C.CMCUST)
