"""
purchasing_plan.py

Reads the Purchasing Dashboard's planning output (inventory_plan_all.xlsx,
regenerated by flooringwebapp.py / mouldingwebapp_refactored.py /
sundrieswebapp_refactored.py via run_webapp_update.ps1) and hands the
demand-health scorer the forward-looking, lead-time-aware numbers it can't
derive from sales history alone:

    lead_time_days / safety_stock / reorder_point / order_up_to_level
        -> an item-specific "how much SHOULD we be holding" target, instead
           of demand_health_scoring.py's own flat 24-month rule of thumb.
    avg_monthly_demand / weekly_fc_mean
        -> forecast demand, so coverage can be computed forward as well as
           backward. For a declining item the forecast rate is lower than
           the trailing rate, so coverage is worse than history implies.
    forecast_wmape / demand_class / adi / cv2
        -> how much to TRUST any of the above. On lumpy, intermittent
           flooring demand the forecast error is frequently >100%, and a
           recommendation resting on a 664%-wMAPE forecast has to be
           labelled as such rather than presented as fact.
    Monthly_Projections
        -> the 12+ month forward inventory path (beginning/ending balance,
           expected arrivals), plus a longer demand history than the
           12-month window the SQL extract pulls.

DESIGN NOTES / TRAPS THIS MODULE HANDLES:

  1. GROUPED SKUS. The plan keys some rows to a slash-joined collection,
     e.g. "RH2SOSNB/RH2SOSNB-20/RH2SOSNB-24" -- one planning row covering
     several item numbers that share inventory. Exploding those onto their
     members duplicates the same quantities N times, which silently
     inflates any total you compute afterwards. Members are expanded so
     they can be joined, but flagged PLAN_SHARED_ROW=1 and the plan SKU is
     kept in PLAN_SKU so callers can de-duplicate before summing.

  2. inventory_position INCLUDES INBOUND PO. It is
     available + on_po - backorder, which is the right measure for a
     purchasing decision but NOT for "dollars sitting on my floor".
     Both are exposed; the caller picks per question.

  3. UOM / LOCATION MISMATCH. The plan works in SF over its own location
     set; demand_health_extract.sql works in billing UOM over locations
     1,3,4,5,6,8,9,51. They agree for most items and disagree wildly for a
     few. check_uom_agreement() flags the outliers so plan-derived
     quantities can be ignored for those rather than producing confident
     nonsense.

  4. MISSING / STALE FILE. The purchasing refresh runs on its own schedule.
     If the file is absent or unreadable this module returns empty frames
     and the scorer transparently falls back to history-only mode -- a
     missing planning file must never take down the daily demand-health run.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import numpy as np
import pandas as pd

METRICS_SHEET = "Inventory_Metrics"
PROJECTIONS_SHEET = "Monthly_Projections"

# Columns lifted from Inventory_Metrics, renamed with a PLAN_ prefix so they
# can never collide with a demand-health column of a similar name.
_METRIC_COLS = {
    "available_sf": "PLAN_AVAILABLE_SF",
    "on_po_sf": "PLAN_ON_PO_SF",
    "backorder_sf": "PLAN_BACKORDER_SF",
    "inventory_position": "PLAN_INV_POSITION",
    "lead_time_days": "PLAN_LEAD_TIME_DAYS",
    "lead_time_source": "PLAN_LEAD_TIME_SOURCE",
    "demand_class": "PLAN_DEMAND_CLASS",
    "adi": "PLAN_ADI",
    "cv2": "PLAN_CV2",
    "forecast_method": "PLAN_FORECAST_METHOD",
    "forecast_wmape": "PLAN_FORECAST_WMAPE",
    "forecast_bias_pct": "PLAN_FORECAST_BIAS_PCT",
    "weekly_fc_mean": "PLAN_WEEKLY_FC_MEAN",
    "avg_monthly_demand": "PLAN_AVG_MONTHLY_DEMAND",
    "avg_weekly_demand": "PLAN_AVG_WEEKLY_DEMAND",
    "safety_stock": "PLAN_SAFETY_STOCK",
    "reorder_point": "PLAN_REORDER_POINT",
    "reorder_quantity": "PLAN_REORDER_QTY",
    "order_up_to_level": "PLAN_ORDER_UP_TO",
    "sku_abc": "PLAN_ABC",
    "first_reorder_month": "PLAN_FIRST_REORDER",
    "sf_per_pallet": "PLAN_SF_PER_PALLET",
    "pallets_per_container": "PLAN_PALLETS_PER_CONTAINER",
}

# Forecast error bands. wMAPE is a percentage here (119 == 119% error).
# These are deliberately generous: on intermittent B2B flooring demand even
# a good model lands well above what a retail forecaster would accept.
WMAPE_GOOD = 50.0
WMAPE_FAIR = 100.0

# Outside this band, plan SF and SQL billing-UOM quantities are not
# describing the same thing and plan quantities shouldn't be trusted.
UOM_RATIO_LOW = 0.5
UOM_RATIO_HIGH = 2.0


def empty_plan() -> pd.DataFrame:
    """An empty plan frame with the right columns, for the no-file case."""
    cols = ["ITEM_NUMBER", "PLAN_SKU", "PLAN_SHARED_ROW"] + list(_METRIC_COLS.values())
    return pd.DataFrame({c: pd.Series(dtype="object") for c in cols})


def confidence_tier(wmape: float, demand_class: str | None = None) -> str:
    """
    Turn forecast error into a plain-language trust label. Anything worse
    than FAIR means the forward-looking numbers are indicative at best and
    the decision should rest on actual sales history instead.
    """
    if wmape is None or (isinstance(wmape, float) and np.isnan(wmape)):
        return "unknown"
    if wmape <= WMAPE_GOOD:
        return "good"
    if wmape <= WMAPE_FAIR:
        return "fair"
    return "poor"


def load_plan(path: str | Path) -> tuple[pd.DataFrame, dict, dict]:
    """
    Returns (metrics, projections, meta).

      metrics     one row per ITEM_NUMBER (grouped plan rows expanded onto
                  their members, flagged via PLAN_SHARED_ROW).
      projections {ITEM_NUMBER: {"history": [...], "forecast": [...]}} where
                  each entry is {"month": "YYYY-MM", "value": float} and the
                  forecast entries also carry "ending_inventory".
      meta        {"available": bool, "path", "modified", "age_days",
                   "n_plan_skus", "n_items", "note"}
    """
    p = Path(path)
    meta: dict = {
        "available": False,
        "path": str(p),
        "modified": None,
        "age_days": None,
        "n_plan_skus": 0,
        "n_items": 0,
        "note": "",
    }

    if not p.exists():
        meta["note"] = (
            f"{p.name} not found -- running history-only. Planning columns "
            "(lead time, safety stock, order-up-to, forecast) will be blank."
        )
        return empty_plan(), {}, meta

    try:
        raw = pd.read_excel(p, METRICS_SHEET)
    except Exception as exc:  # unreadable / locked by Excel / sheet renamed
        meta["note"] = f"Could not read {p.name} [{METRICS_SHEET}]: {exc}. Running history-only."
        return empty_plan(), {}, meta

    missing = [c for c in ("sku", "order_up_to_level") if c not in raw.columns]
    if missing:
        meta["note"] = (
            f"{p.name} is missing required column(s) {missing} -- the purchasing "
            "dashboard's output format may have changed. Running history-only."
        )
        return empty_plan(), {}, meta

    mtime = dt.datetime.fromtimestamp(p.stat().st_mtime)
    meta.update(
        available=True,
        modified=mtime.strftime("%Y-%m-%d %I:%M %p"),
        age_days=round((dt.datetime.now() - mtime).total_seconds() / 86400.0, 2),
        n_plan_skus=len(raw),
    )

    keep = {src: dst for src, dst in _METRIC_COLS.items() if src in raw.columns}
    df = raw[["sku", *keep.keys()]].rename(columns=keep).copy()
    df["sku"] = df["sku"].astype(str).str.strip()
    df["PLAN_SHARED_ROW"] = df["sku"].str.contains("/").astype(int)
    df["PLAN_SKU"] = df["sku"]

    # Expand grouped rows onto their member item numbers so they can join,
    # keeping PLAN_SKU/PLAN_SHARED_ROW so totals can be de-duplicated later.
    df["ITEM_NUMBER"] = df["sku"].str.split("/")
    df = df.explode("ITEM_NUMBER")
    df["ITEM_NUMBER"] = df["ITEM_NUMBER"].astype(str).str.strip()
    df = df[df["ITEM_NUMBER"] != ""].drop(columns=["sku"])
    # A member appearing in two plan rows would silently pick one; keep the
    # row with the larger position so we err toward flagging overstock.
    if "PLAN_INV_POSITION" in df.columns:
        df = df.sort_values("PLAN_INV_POSITION", ascending=False)
    df = df.drop_duplicates(subset=["ITEM_NUMBER"], keep="first").reset_index(drop=True)

    if "PLAN_FIRST_REORDER" in df.columns:
        df["PLAN_FIRST_REORDER"] = pd.to_datetime(
            df["PLAN_FIRST_REORDER"], errors="coerce"
        ).dt.strftime("%Y-%m")
    if "PLAN_FORECAST_WMAPE" in df.columns:
        df["PLAN_FORECAST_CONFIDENCE"] = [
            confidence_tier(w) for w in df["PLAN_FORECAST_WMAPE"]
        ]
    else:
        df["PLAN_FORECAST_CONFIDENCE"] = "unknown"

    meta["n_items"] = len(df)
    projections = _load_projections(p, df)
    return df, projections, meta


def _load_projections(path: Path, metrics: pd.DataFrame) -> dict:
    """
    Monthly_Projections carries BOTH the historical demand series (longer
    than the 12-month SQL window) and the forward forecast path. Rows are
    distinguished by which column is populated: 'Historical Demand' for the
    past, 'Forecast' for the future.
    """
    try:
        pr = pd.read_excel(path, PROJECTIONS_SHEET)
    except Exception:
        return {}
    if "SKU" not in pr.columns or "Month" not in pr.columns:
        return {}

    pr = pr.copy()
    pr["SKU"] = pr["SKU"].astype(str).str.strip()
    pr["Month"] = pd.to_datetime(pr["Month"], errors="coerce")
    pr = pr.dropna(subset=["Month"]).sort_values(["SKU", "Month"])

    # Map plan SKU -> member item numbers (reverse of the explode above).
    members: dict[str, list[str]] = {}
    for item, plan_sku in zip(metrics["ITEM_NUMBER"], metrics["PLAN_SKU"]):
        members.setdefault(plan_sku, []).append(item)

    hist_col = "Historical Demand" if "Historical Demand" in pr.columns else None
    fc_col = "Forecast" if "Forecast" in pr.columns else None
    end_col = "Ending Inventory" if "Ending Inventory" in pr.columns else None

    pr["_month_label"] = pr["Month"].dt.strftime("%Y-%m")

    out: dict = {}
    for sku, grp in pr.groupby("SKU", sort=False):
        targets = members.get(sku)
        if not targets:
            continue

        history = []
        if hist_col:
            h = grp[grp[hist_col].notna()]
            history = [
                {"month": mo, "value": float(v)}
                for mo, v in zip(h["_month_label"], h[hist_col])
            ]

        forecast = []
        if fc_col:
            f = grp[grp[fc_col].notna()]
            for mo, v, end in zip(
                f["_month_label"],
                f[fc_col],
                f[end_col] if end_col else [np.nan] * len(f),
            ):
                entry = {"month": mo, "value": float(v)}
                if end is not None and pd.notna(end):
                    entry["ending_inventory"] = float(end)
                forecast.append(entry)

        if not history and not forecast:
            continue
        payload = {"history": history, "forecast": forecast}
        for item in targets:
            out[item] = payload
    return out


def check_uom_agreement(
    merged: pd.DataFrame,
    plan_qty_col: str = "PLAN_AVAILABLE_SF",
    sql_qty_col: str = "AVAIL_QTY",
) -> pd.Series:
    """
    1 where the plan's quantity and the SQL extract's quantity are close
    enough to be describing the same thing, 0 where they disagree badly
    enough that plan-derived quantities shouldn't be used for that item.
    Items with no plan row, or with zero stock on either side, return 0.
    """
    if plan_qty_col not in merged.columns or sql_qty_col not in merged.columns:
        return pd.Series(0, index=merged.index, dtype=int)
    plan_q = pd.to_numeric(merged[plan_qty_col], errors="coerce")
    sql_q = pd.to_numeric(merged[sql_qty_col], errors="coerce")
    ratio = plan_q / sql_q.replace(0, np.nan)
    ok = ratio.between(UOM_RATIO_LOW, UOM_RATIO_HIGH) & plan_q.notna() & (plan_q > 0)
    return ok.fillna(False).astype(int)
