/* ============================================================
   REP GROUP INVENTORY & SALES QUERIES
   ============================================================
   USAGE:
     - One query per tab in Power Query / Excel
     - Paste each block separately into Power Query's "New Source > OLE DB / ODBC"
     - Items filtered to Division 5 only (IM.IMDIV = 5)
     - QTY_AVAIL_COMPANYWIDE excludes locations 17, 41, 46, 90 (non-selling locations)
     - QTY_OPEN_ORDERS = open customer orders for the rep group's customers
     - QTY_INVOICED = all-time invoiced quantity for the rep group's customers
       To restrict to a date range, add to the SHHEAD join condition:
         AND H.SHIDAT >= DATE('YYYY-01-01')
   ============================================================ */


/* ============================================================
   TAB: DAVE COURTNEY
   REP CODES: 2, 26, 36, 38, 44, 45, 46, 47
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (2, 26, 36, 38, 44, 45, 46, 47)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (2, 26, 36, 38, 44, 45, 46, 47)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: JOSE ZALDIVAR
   REP CODES: 10, 12
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (10, 12)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (10, 12)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: JIM MCCONNELL
   REP CODES: 11, 19
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (11, 19)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (11, 19)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: BRAD ORNELLAS
   REP CODES: 13
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (13)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (13)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: ANDY AGUILAR
   REP CODES: 14, 15, 20
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (14, 15, 20)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (14, 15, 20)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: WARREN CARMICHAEL
   REP CODES: 18
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (18)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (18)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: DENISE SOLIS
   REP CODES: 105
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (105)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (105)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: CHRIS PHILLIPS
   REP CODES: 106
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (106)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (106)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: HOUSE ACCOUNT
   REP CODES: 818, 880, 888
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (818, 880, 888)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN IN (818, 880, 888)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;


/* ============================================================
   TAB: OTHER
   ALL REP CODES NOT IN:
     2, 10, 11, 12, 13, 14, 15, 18, 19, 20, 26, 36, 38,
     44, 45, 46, 47, 105, 106, 818, 880, 888
   ============================================================ */
SELECT
    TRIM(IM.IMITEM)         AS ITEM_NUMBER,
    TRIM(IM.IMDESC)         AS DESCRIPTION,
    COALESCE(MAX(OO.QTY_OPEN_ORDERS), 0)          AS QTY_OPEN_ORDERS,
    COALESCE(MAX(SH.QTY_INVOICED), 0)             AS QTY_INVOICED,
    SUM(CASE WHEN B.IBLOC NOT IN (17,41,46,90) THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_COMPANYWIDE,
    SUM(CASE WHEN B.IBLOC = 1  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC1,
    SUM(CASE WHEN B.IBLOC = 3  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC3,
    SUM(CASE WHEN B.IBLOC = 4  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC4,
    SUM(CASE WHEN B.IBLOC = 5  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC5,
    SUM(CASE WHEN B.IBLOC = 6  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC6,
    SUM(CASE WHEN B.IBLOC = 8  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC8,
    SUM(CASE WHEN B.IBLOC = 9  THEN B.IBQOH - B.IBQOO ELSE 0 END) AS QTY_AVAIL_LOC9
FROM GSFL2K.ITEMMAST IM
LEFT JOIN GSFL2K.ITEMBAL B
    ON  TRIM(B.IBITEM) = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.OLITEM)      AS ITEM,
        SUM(L.OLBLUO)       AS QTY_OPEN_ORDERS
    FROM GSFL2K.OOLINE L
    JOIN GSFL2K.OOHEAD H
        ON  H.OHORD# = L.OLORD#
        AND H.OHLOC  = L.OLLOC
        AND H.OHCO   = L.OLCO
    WHERE TRIM(H.OHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN NOT IN (2, 10, 11, 12, 13, 14, 15, 18, 19, 20, 26, 36, 38, 44, 45, 46, 47, 105, 106, 818, 880, 888)
    )
      AND H.OHOTYP NOT LIKE '%RA%'
      AND H.OHCUST NOT LIKE '%TRANSFER%'
    GROUP BY TRIM(L.OLITEM)
) OO ON OO.ITEM = TRIM(IM.IMITEM)
LEFT JOIN (
    SELECT
        TRIM(L.SLITEM)      AS ITEM,
        SUM(L.SLBLUO)       AS QTY_INVOICED
    FROM GSFL2K.SHLINE L
    JOIN GSFL2K.SHHEAD H
        ON  H.SHCO   = L.SLCO
        AND H.SHLOC  = L.SLLOC
        AND H.SHORD# = L.SLORD#
        AND H.SHINV# = L.SLINV#
    WHERE TRIM(H.SHCUST) IN (
        SELECT TRIM(CMCUST)
        FROM GSFL2K.CUSTMAST
        WHERE CMSLMN NOT IN (2, 10, 11, 12, 13, 14, 15, 18, 19, 20, 26, 36, 38, 44, 45, 46, 47, 105, 106, 818, 880, 888)
    )
    GROUP BY TRIM(L.SLITEM)
) SH ON SH.ITEM = TRIM(IM.IMITEM)
WHERE IM.IMDIV = 5
GROUP BY
    TRIM(IM.IMITEM),
    TRIM(IM.IMDESC)
ORDER BY
    TRIM(IM.IMITEM)
;
