# setup_demand_health_refresh_task.ps1
#
# Creates (or replaces) a Windows scheduled task that runs the Demand
# Health refresh. Mirrors setup_omp_refresh_task.ps1 -- does NOT require
# Administrator rights, and is fully visible in Task Scheduler without
# elevation.
#
# Run this ONCE (from any regular PowerShell prompt, no "Run as
# Administrator" needed):
#   PowerShell -ExecutionPolicy Bypass -File ".\setup_demand_health_refresh_task.ps1"
#
# WHY TWO TIMES A DAY (06:30 and 15:00):
#   06:30 - the dashboard is already refreshed and waiting when you start
#           your day. Sales numbers are same-morning fresh. The planning
#           columns (lead time, safety stock, reorder point, order-up-to)
#           come from inventory_plan_all.xlsx, which at that hour is still
#           yesterday afternoon's copy -- fine, because those figures move
#           slowly, but it is a day behind.
#   15:00 - the "OMP Dashboard Refresh" task regenerates
#           inventory_plan_all.xlsx starting at 11:00 and 14:00, and takes
#           roughly 45-55 minutes (measured from refresh_log.txt). Running
#           at 15:00 means the 14:00 purchasing rebuild has comfortably
#           finished, so sales history AND planning data are both same-day.
#           This is the run whose overstock/understock calls are most
#           trustworthy.
#
# To use different times, pass your own list:
#   PowerShell -ExecutionPolicy Bypass -File ".\setup_demand_health_refresh_task.ps1" -Times "07:00","15:30"
#
# To run once daily instead:
#   PowerShell -ExecutionPolicy Bypass -File ".\setup_demand_health_refresh_task.ps1" -Times "15:00"
#
# To remove the task later:
#   Unregister-ScheduledTask -TaskName "OMP Demand Health Refresh" -Confirm:$false

param(
    [string[]]$Times = @("06:30", "15:00")
)

$TaskName = "OMP Demand Health Refresh"
$RepoDir  = "H:\2025\NewForecastingModel\OMPforecasting5"
$Script   = "$RepoDir\run_demand_health_refresh.ps1"
$LogFile  = "$RepoDir\demand_health_refresh_log.txt"
$PlanFile = "$RepoDir\inventory_plan_all.xlsx"

if (-not (Test-Path $Script)) {
    Write-Error "Script not found: $Script"
    exit 1
}

# The action: run PowerShell non-interactively.
# Logging is handled inside the script itself (Add-Content to demand_health_refresh_log.txt).
$psArgs = "-NonInteractive -ExecutionPolicy Bypass -File `"$Script`""
$action = New-ScheduledTaskAction `
    -Execute    "powershell.exe" `
    -Argument   $psArgs `
    -WorkingDirectory $RepoDir

# One trigger per requested time
$triggers = @()
foreach ($t in $Times) {
    $triggers += New-ScheduledTaskTrigger -Daily -At $t
}

# Settings: 30-minute timeout (this refresh takes well under a minute), skip
# if a previous run is somehow still going, catch up if the machine was
# off/asleep at trigger time
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit     (New-TimeSpan -Minutes 30) `
    -MultipleInstances      IgnoreNew `
    -StartWhenAvailable     `
    -RunOnlyIfNetworkAvailable

# Principal: current interactive user, no elevation required
$principal = New-ScheduledTaskPrincipal `
    -UserId    "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel  Limited

# Register (overwrites if task already exists under this user)
Register-ScheduledTask `
    -TaskName  $TaskName `
    -Action    $action `
    -Trigger   $triggers `
    -Settings  $settings `
    -Principal $principal `
    -Force | Out-Null

Write-Host ""
Write-Host "Task registered: $TaskName"
Write-Host "  Runs as    : $env:USERDOMAIN\$env:USERNAME"
Write-Host "  Triggers   : $($Times -join ' and ') daily"
Write-Host "  Script     : $Script"
Write-Host "  Log        : $LogFile"
Write-Host ""

if (Test-Path $PlanFile) {
    $planAge = [math]::Round(((Get-Date) - (Get-Item $PlanFile).LastWriteTime).TotalHours, 1)
    Write-Host "Purchasing plan data: inventory_plan_all.xlsx is $planAge hours old."
    Write-Host "  (regenerated by the 'OMP Dashboard Refresh' task at 11:00 and 14:00)"
} else {
    Write-Host "NOTE: inventory_plan_all.xlsx not found in $RepoDir."
    Write-Host "  Demand health will still run, but without lead time / safety stock /"
    Write-Host "  reorder point / order-up-to level, so overstock falls back to a flat"
    Write-Host "  24-month rule and understock detection is unavailable."
}
Write-Host ""
Write-Host "Note: this task runs under your Windows login, same as the existing"
Write-Host "'OMP Dashboard Refresh' task -- it only fires if you're logged in."
Write-Host "If your machine is off or locked at those times, it catches up as soon"
Write-Host "as you log back in (StartWhenAvailable)."
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Run now  : Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  Check    : Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "  View log : notepad '$LogFile'"
Write-Host "  Remove   : Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
Write-Host ""
